# Generated by Django 5.2.4 on 2026-07-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='reset_token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
