# Generated by Django 5.2.4 on 2026-07-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_minimum_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
